### ISSUE TITLE
[TMP] MainViewModel 개발

### ISSUE THREAD

**Issue by Lagnesia** [mercy-project/Mercy-Kids-Client#11]
#### 1. 작업 대상이 무엇인가요?
[] 신규 기능 개발 [MainViewModel.kt 작성]
[] 기존 프로젝트 개선

#### 2. 작업사항에 대해 간략히 설명해주세요.
> 간단하게 적어주세요. 테스트용.

**Comment by skfo763** [comment]
이슈 템플릿을 채워주시고 작업자를 배정해주세요!

**Comment by skfo763** [comment]
![image](https://user-images.githubusercontent.com/42145106/107040691-eec45680-6802-11eb-81f0-7a98e99c0fb8.png)

작업자는 이쪽 화면에서 톱니바퀴 버튼을 누르면 찾을 수 있습니다.
